### ISSUE TITLE
Property WorldEntity.Position should be Vector2Int, not Vector3Int

### ISSUE THREAD

**Issue by MatthewGoff** [JBoggsy/AutoTown#5]
I'm not sure if you had a specific reason for Vector3Int, or you didn't know Vector2Int was available.

**Comment by JBoggsy** [comment]
Would like to retain flexibiity in case I shift to voxels or other 3D world representation later

**Comment by JBoggsy** [comment]
Would like to retain flexibiity in case I shift to voxels or other 3D world representation later
